export const dormAndFloorData = {
  "Away From Campus": ["Upland (abroad)"],
  "Bergwall Hall": ["1st Bergwall", "2nd Bergwall", "3rd Bergwall", "4th Bergwall"],
  "Breuninger Hall": ["1st Breuninger", "2nd Breuninger", "3rd Breuninger"],
  "Brolund Hall": ["Residential Village Wing 6"],
  "Campbell Hall": ["Univ Apts-Campbell Hall-1st Fl", "Univ Apts-Campbell Hall-2nd Fl"],
  "Chiu Hall": ["Residential Village Wing 1"],
  "Commuter": ["Married", "Single"],
  "Corner House": ["Corner House Wing"],
  "Delta Apts": ["Delta Wing"],
  "English Hall": [
    "1st English", "2nd English", "3rd English", "4th English"
  ],
  "Fairlane Apts": ["Fairlane Wing"],
  "Fishback Hall": ["1st Fishback", "2nd Fishback", "3rd Fishback"],
  "Freebeck Hall": ["Residential Village Wing 2"],
  "Gallery Apts": ["Gallery Wing"],
  "Golden Apts": ["Golden Wing"],
  "Gridley House": ["Gridley House Wing"],
  "Harding Hall": ["1st Harding", "2nd Harding", "3rd Harding"],
  "Harvey Hall": ["1st Harvey", "2nd Harvey", "3rd Harvey"],
  "Hensley Hall": ["Residential Village Wing 7"],
  "Hoover Apts": ["Hoover Wing"],
  "Lindner Hall": ["Residential Village Wing 3"],
  "Mahre Apts": ["Mahre Wing"],
  "May Apts": ["May Wing"],
  "McFarlane Apts": ["McFarlane Wing"],
  "McKenna Hall": ["Residential Village Wing 4"],
  "McPherson Apts": ["McPherson Wing"],
  "Metcalf Hall": ["1st Metcalf", "2nd Metcalf", "3rd Metcalf"],
  "Morley Apts": ["Morley Wing"],
  "Morris Hall": ["1st Morris", "2nd Morris", "3rd Morris", "4th Morris"],
  "Off Campus": ["Apt", "House", "Upland", "Other", "Abroad"],
  "Olson Hall": ["1st Olson", "2nd Olson", "3rd Olson", "4th Olson"],
  "Rauch Apts": ["Rauch Wing"],
  "Saint Clair Apts": ["Saint Clair Wing"],
  "Samuelson Hall": ["1st Samuelson", "2nd Samuelson", "3rd Samuelson"],
  "Siberian Bell Tower": ["Siberian Bell Tower Wing"],
  "Spaulding Apts": ["Spaulding Wing"],
  "Strafford Apts": ["Strafford Wing"],
  "Swallow Robin Hall": ["1st Swallow", "2nd Swallow", "3rd Swallow"],
  "Test Dorm": ["Test Wing"],
  "Tian Hall": ["Residential Village Wing 5"],
  "Upland Manor Apts": ["Upland Manor Wing"],
  "Watson Hall": ["1st Watson", "2nd Watson", "3rd Watson"],
  "Wilson Hall": ["Residential Village Wing 8"],
  "Wolgemuth Hall": ["1st Wolgemuth", "2nd Wolgemuth", "3rd Wolgemuth"],
  "Wright Morris Hall": ["1st Wright Morris", "2nd Wright Morris", "3rd Wright Morris"],
  "Zadrowski Apts": ["Zadrowski Wing"]
};